config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root 'trips#index', as: :authenticated_root
  end

  get 'find_trips' => 'trips#find_trips'
  get 'search' => 'trips#search'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :trip
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'
end

app/models/trip.rb
class Trip < ApplicationRecord

  scope :available, -> do
    where("start_date >= ? and user_id is null", Date.today).order("created_at DESC")
  end

  def self.search(trip_params)
    query = ""
    if trip_params[:price].present?
      query << "and price <= #{trip_params[:price].to_i} "
    elsif trip_params[:number].present?
      query << "and number_of_member = #{trip_params[:number].to_i} "
    elsif trip_params[:start_date].present?
      query << "and start_date = '#{trip_params[:start_date].to_date}' "
    elsif trip_params[:end_date].present?
      query << "and end_date = '#{trip_params[:end_date].to_date}' "
    end
    query.empty? ? [] : where("user_id is null #{query}")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trips

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def edit
  end


  def create
    if current_user
      @comment = Comment.new(comment_params)
      @comment.user_id = current_user.id
      @comment.trip_id = params[:tripid]
      respond_to do |format|
        if @comment.save
          format.html { redirect_to '/', notice: 'Comment is successfully created.' }
        else
          format.html { redirect_to '/', notice: 'Please provide valid details.'}
        end
      end

    else
      #This method depends whether user has to be known to comment or not.
      # Currently its implemented to redirect user to sign up page first if he/she has'nt logged in
      respond_to do |format|
        format.html { redirect_to '/users/sign_in', notice: 'Please login first to comment on post.'}
       end

    end
  end

  def update
    if current_user.id == @comment.user_id
      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to '/', notice: 'Comment is successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    else
      respond_to do |format|
        # Only user who has commented can update it but functionality can be changed so admin and moderators can do the same too
        format.html { redirect_to '/',notice: 'You are not authorized to update comment' }
      end

    end
  end

  def destroy
    if current_user.id == @comment.user.id
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to '/', notice: 'Comment is successfully destroyed.' }
      end
    else
      respond_to do |format|
        # Only user who has commented can delete it but functionality can be changed so admin and moderators can do the same too
        format.html { redirect_to '/',notice: 'You are not authorized to delete comment' }
      end
    end

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:comment_text, :user_id, :trip_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index

  end

  def find_trips
    @trips = Trip.available
  end

  def search
    @trips = Trip.available.search(params[:trip]) if params[:trip]
    if @trips.empty?
      flash.now[:alert] = "There are no results for your search"
    end
    render 'find_trips'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/home/index.html.slim
  head
    style
      |  .navbar-toggler { z-index: 1; } @media (max-width: 576px) { nav > .container { width: 100%; } } 
  body#page-top
    header.masthead
      .header-content
        .header-content-inner
          h1#homeHeading
            | Where to share the journey, where to trace your journey 
          hr
          p
            | Many places are waiting for you to come, share your bows, write your life, show people your happy life. 
          a.btn.btn-primary.btn-xl[href="#about"]
            | Discover now
    section#about.bg-primary
      .container
        .row
          .col-lg-8.offset-lg-2.text-center
            h2.section-heading.text-white
              | We have everything you need! 
            hr.light
            p.text-faded
              | Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!
            = link_to "Discover now", new_user_session_path, class: 'btn btn-info btn-xl sr-button'
    section#services
      .container
        .row
          .col-lg-12.text-center
            h2.section-heading
              | At Your Service
            hr.primary
      .container
        .row
          .col-lg-3.col-md-6.text-center
            .service-box
              i.fa.fa-4x.fa-diamond.text-primary.sr-icons
              h3
                | Sturdy Templates
              p.text-muted
                | Our templates are updated regularly so they don't break.
          .col-lg-3.col-md-6.text-center
            .service-box
              i.fa.fa-4x.fa-paper-plane.text-primary.sr-icons
              h3
                | Ready to Ship
              p.text-muted
                | You can use this theme as is, or you can make changes!
          .col-lg-3.col-md-6.text-center
            .service-box
              i.fa.fa-4x.fa-newspaper-o.text-primary.sr-icons
              h3
                | Up to Date
              p.text-muted
                | We update dependencies to keep things fresh.
          .col-lg-3.col-md-6.text-center
            .service-box
              i.fa.fa-4x.fa-heart.text-primary.sr-icons
              h3
                | Made with Love
              p.text-muted
                | You have to make your websites with love these days!
    section#contact
      .container
        .row
          .col-lg-8.offset-lg-2.text-center
            h2.section-heading
              | Let's Get In Touch!
            hr.primary
            p
              | Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!
          .col-lg-4.offset-lg-2.text-center
            i.fa.fa-phone.fa-3x.sr-contact
            p
              | 123-456-6789
          .col-lg-4.text-center
            i.fa.fa-envelope-o.fa-3x.sr-contact
            p
              a[href="mailto:your-email@your-domain.com"]
                | feedback@startbootstrap.com
    script[src="vendor/jquery-easing/jquery.easing.min.js"]
    script[src="vendor/scrollreveal/scrollreveal.min.js"]
    script[src="vendor/magnific-popup/jquery.magnific-popup.min.js"]
    script[src="js/creative.min.js"]

app/views/layouts/_navbar.html.slim
nav#mainNav.navbar.fixed-top.navbar-toggleable-md.navbar-light
  button.navbar-toggler.navbar-toggler-right[type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  .container
    a.navbar-brand[href="/"]
      = I18n.t 'tbp'
    #navbarExample.collapse.navbar-collapse
      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item
            = link_to (I18n.t 'find trips'), find_trips_path, class: 'nav-link'
          li.nav-item
            = link_to (I18n.t 'post'), "/", class: 'nav-link'
          li.nav-item
            = link_to (I18n.t 'notification'), "/", class: 'nav-link'
          li.nav-item
            = link_to (I18n.t 'signout'), destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item
            = link_to (I18n.t 'about'), new_user_session_path, class: 'nav-link'
          li.nav-item
            = link_to (I18n.t 'signin'), new_user_session_path, class: 'nav-link'
          li.nav-item
            = link_to (I18n.t 'contact'), new_user_session_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = I18n.t 'tbp'
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navbar'
    = yield
    = javascript_pack_tag 'application'

app/views/trips/find_trips.html.slim
= form_tag("/search", method: "get", enforce_utf8: false) do
  .container
    .row
      .col-lg-3.col-md-6.col-md-offset-3.col-lg-offset-0
        .well
          h3 align="center"  Find trips
          form.form-horizontal
            .form-group
              label.control-label for="price"  Price
              .input-group
                #basic-addon2.input-group-addon
                  span.glyphicon.glyphicon-usd
                = number_field_tag 'trip[price]', class: 'form-control'
            .form-group
              label.control-label for="number-of-members"  Number of members
              .input-group
                #basic-addon2.input-group-addon
                  span.glyphicon.glyphicon-user
                = number_field_tag 'trip[number]', class: 'form-control'
            .form-group
              label.control-label for="start-date"  Start date
              .input-group
                #basic-addon2.input-group-addon
                  span.glyphicon.glyphicon-calendar
                = date_field_tag 'trip[start_date]', class: 'form-control'
            .form-group
              label.control-label for="end-date"  End date
              .input-group
                #basic-addon2.input-group-addon
                  span.glyphicon.glyphicon-calendar
                = date_field_tag 'trip[end_date]', class: 'form-control'
            p.text-center
              = submit_tag('Search', name: nil, class: "btn btn-danger")
      .col
        .well
          - if flash[:alert]
            .alert.alert-warning role="alert"
              strong We`re sorry.
              = flash[:alert]

          h2 Available trips
          table.table.table-hover
            thead
              tr
                th Title
                th Price
                th Time spone
            tbody
              - @trips && @trips.each do |trip|
                tr
                  td = trip.title
                  td = trip.price
                  td = "#{trip.start_date} - #{trip.end_date}"

app/views/trips/index.html.slim
.container.page
  .row
    - @trips.each do |trip|
      .col-md-6
        .card
          = image_tag(trip.image, :class => 'card-img-top img-fluid')
          .card-body
            h4.card-title 
              = trip.title
            p.card-text
              = truncate(trip.body, length: 100)
            p.card-text
              = fa_icon "money"
              = trip.price
            p.card-text
              = fa_icon "clock-o"
              = " #{trip.start_date} - #{trip.end_date}"
            a.btn.btn-primary href="#"  Details

app/views/trips/new.html.slim
.container.box-center
  .row
    .col-md-8
      h3 New Trip
      = form_for @trip do |f|
        .form-group
          = f.label :title
          = f.text_field :title, :class => 'form-control'

        .form-group
          = f.label :body
          = f.text_area :body, :class => 'form-control'

        .form-group
          = f.label :price
          = f.text_field :price, :class => 'form-control'
        
        .form-group
          = f.label :start_date
          = f.date_field :start_date, :class => 'form-control'

        .form-group
          = f.label :end_date
          = f.date_field :end_date, :class => 'form-control'

        .form-group
          = f.label :number_of_member
          = f.number_field :number_of_member, :class => 'form-control'
        
        .form-group
          = f.label :image
          = f.file_field :image, :class => 'form-control'

        = f.submit 'Post Trip', :class => 'btn btn-primary'